targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
      json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
          include_if_null: false
